import Head from "next/head";
import { Inter } from "@next/font/google";
import { css } from "@emotion/react";
import styled from "@emotion/styled";

const inter = Inter({ subsets: ["latin"] });

const style = css`
  background-color: white;
  color: cornflowerblue;
  border: 1px solid lightgreen;
  border-right: none;
  border-bottom: none;
  box-shadow: 5px 5px 0 0 lightgreen, 10px 10px 0 0 lightyellow;
  transition: all 0.1s linear;
  margin: 3rem 0;
  padding: 1rem 0.5rem;
`;

const Basic = styled.div`
  ${style}
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Basic>Hello, world!</Basic>
      </main>
    </>
  );
}
