name: Pull Request
on:
  pull_request:
    
jobs:
  pull_request:
    runs-on: ubuntu-20.04
    name: Build, Test and Lint

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching NPM packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ secrets.CACHE_KEY }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ secrets.CACHE_KEY }}-yarn-

      - name: Caching Gatsby
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ secrets.CACHE_KEY }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ secrets.CACHE_KEY }}-gatsby-build-

      - run: yarn install
      - run: yarn lint
      - run: yarn build
        env:
            GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
            CI: true
      - run: yarn test

      - name: Upload website
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: firebase
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount:
            '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BJERK_IO }}'
          projectId: bjerk-io
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Get all urls from sitemap.xml
        id: parse-sitemap
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: cobraz/parse-sitemap@main
        with:
          sitemap-url: ${{ steps.firebase.outputs.details_url }}/sitemap/sitemap-index.xml
          replace-domain: https://bjerk.io|${{ steps.firebase.outputs.details_url }}

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@8.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          urls: ${{ steps.parse-sitemap.outputs.urls }}
          uploadArtifacts: true
          temporaryPublicStorage: true
