name: Pull Request
on:
  pull_request:

jobs:
  pull_request:
    runs-on: ubuntu-20.04
    name: Build, Test and Lint

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key:
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{
            hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - run: yarn install
      - run: yarn lint
      - run: yarn build

      - name: Upload website
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: firebase
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount:
            '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BJERK_IO }}'
          projectId: bjerk-io
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      # - name: Get all urls from sitemap.xml
      #   id: parse-sitemap
      #   if: ${{ github.actor != 'dependabot[bot]' }}
      #   uses: cobraz/parse-sitemap@main
      #   with:
      #     sitemap-url: ${{ steps.firebase.outputs.details_url }}/sitemap/sitemap-index.xml
      #     replace-domain: https://bjerk.io|${{ steps.firebase.outputs.details_url }}

      # - name: Run Lighthouse
      #   uses: treosh/lighthouse-ci-action@v7
      #   if: ${{ github.actor != 'dependabot[bot]' }}
      #   with:
      #     urls: ${{ steps.parse-sitemap.outputs.urls }}
      #     uploadArtifacts: true
      #     temporaryPublicStorage: true
