name: Deploy to dev.bjerk.io
on:
  push:
    branches:
      - next
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key:
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{
            hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Upload website
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount:
            '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BJERK_IO }}'
          channelId: live
          target: dev
          projectId: bjerk-io
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
